export const pools = ["Aryans", "Kshatriyas", "Nawabs", "Peshwas", "Shauryas"];
export const clubs = [
  "Aeromodelling Club",
  "Astronomy Club",
  "Business Club",
  "Coding Club",
  "Debating Society",
  "Design Club",
  "Economics Club",
  "Electronics Club",
  "Entrepreneurship Cell",
  "Finance Club",
  "Fine Arts Club",
  "Literary Society",
  "Music Club",
  "Photography Club",
  "Quiz Club",
  "Robotics Club",
  "Science Club",
  "Social Service Club",
  "Sports Club",
  "Drama Club",
];
